### ISSUE TITLE
Performance Tests

### ISSUE THREAD

**Issue by finleymercyabraham** [amosproj/amos-ss2021-synthetic-file-system#59]
## Problems to solve:
To have a clear idea about the performance of the SFS
## Further details:
Testing of READ file functionalities 
## Proposals:
Getting a performance evaluation with dbench  

## Acceptance criteria
Comparison of the benchmarks in the SFS and raw version.

## Definition of done

      1. Code review from peers has been completed and passed
        a. Code is fully implemented and commented
        b. Adheres to coding guidelines
        c. Commits are not squashed
        d. Code is checked into the repository
    2. Unit tests/ Integration test have been written and are passing
    3. Cleanliness of the Code
    4. No critical bugs are open
    5. Documentation has been updated
    6. Code has been included into the release (candidate)
    7. Code Coverage:
         40 % - for Features
         50 % - for Sprint Release
         60 % - for Product Release

**Comment by vaidehi-for-coding** [comment]
[PERFORMANCE TESTS WITH IOZONE.docx](https://github.com/amosproj/amos-ss2021-synthetic-file-system/files/6689187/PERFORMANCE.TESTS.WITH.IOZONE.docx)

Did basic performance testing using IOZONE. Uploading results.

**Comment by vaidehi-for-coding** [comment]
[perf-tests-results.xlsx](https://github.com/amosproj/amos-ss2021-synthetic-file-system/files/6766255/perf-tests-results.xlsx)
Attaching the dismal results fuse sfs gave against ext4. The document attached earlier apparently had the iozone command run incorrectly. Instead of running iozone /path_to_mount_point, I should have directly gone under the mountpoint and then run the iozone command, as iozone runs the tests on the file system the current directory being used. The results seem really dismal, but after looking up various sources online including a few papers regarding usage of iozone for diiferent file systems as well as running the tests again and again with the results kind of being in the same number range, I'm submitting this excel file with the final results.
